[package]
name = "graph_gen"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.35", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
uuid = {version = "1.16.0", features = ["v4"]}
rand = "0.9.0"
